#!/bin/sh

echo "*************************************************"
echo "*****        x-Boot building, ver 0.1       *****" 
echo "*************************************************"

echo "*** cleaning..."
rm -rf ./_build
rm -rf ./_install

if [ "$1" != "clean" ]; then

echo ""
echo "*** pre-building..."
mkdir -pv ./_build
mkdir -pv ./_install

cd _build

if [ "x$CC" = "x" ]; then
    echo Guessing CC
    export CC=/opt/arm-2010.09/bin/arm-none-linux-gnueabi-gcc
fi

cmake .. -DCMAKE_INSTALL_PREFIX=../_install -DCMAKE_BUILD_TYPE=RELEASE

echo ""
echo "*** building..."
make
make install

cd ..

echo ""
echo "*** conversion..."
echo ./elftosb2 -z -c ./imx233_uboot.db -o ./_install/bin/uboot.sb
./elftosb2 -z -c ./imx233_uboot.db -o ./_install/bin/uboot.sb

echo ""
echo "*** built results..."
ls -l ./_install/bin/*
md5sum ./_install/bin/*
md5sum ./_install/lib/*


fi
