set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1.1)

set(CMAKE_SYSTEM_PROCESSOR arm)

set(CROSS_COMPILER_PATH "/opt/arm-2010.09")
set(CROSS_COMPILER_PREFIX "arm-none-linux-gnueabi")

set(CMAKE_C_COMPILER "${CROSS_COMPILER_PATH}/bin/${CROSS_COMPILER_PREFIX}-gcc")
set(CMAKE_FIND_ROOT_PATH "${CROSS_COMPILER_PATH}/${CROSS_COMPILER_PREFIX}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
