#!/bin/sh

echo "*************************************************"
echo "*****        u-Boot building, ver 0.1       *****" 
echo "*************************************************"

echo "*** cleaning..."
echo "make distclean"
./clean
make CROSS_COMPILE=/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi- distclean
cd ./hw
make clean

echo " "
echo "*** building hw binaries..."
make CROSS_COMPILE=/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-
cd ../

echo " "
echo "*** building stmp378x_dev_config..."
echo "make stmp378x_dev_config"
make -j2 CROSS_COMPILE=/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi- stmp378x_dev_config


echo " "
echo "*** building..."
echo "make"
make -j2 CROSS_COMPILE=/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi- 

echo " "
echo "*** conversion..."
echo ./elftosb2 -z -c ./imx233_uboot.db -o uboot.sb
./elftosb2 -z -c ./imx233_uboot.db -o uboot.sb

echo " "
echo "*** storing..."
echo mkdir bin
mkdir -p bin
echo mv uboot.sb ./bin/
mv uboot.sb u-boot.* u-boot System.map ./bin/
