#!/bin/sh
  
#!/bin/sh

echo "*************************************************"
echo "*****        u-Boot cleaning, ver 0.1       *****" 
echo "*************************************************"

echo "*** cleaning..."

echo "make clean"
cd ./hw
make clean
cd ../

make CROSS_COMPILE=/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi- clean

echo "make distclean"
make CROSS_COMPILE=/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi- distclean

rm -rf ./bin

rm power_prep

cd ./tools/
rm *.o mkimage img2srec *.a

cd ../lib_generic/
rm *.o *.a ./lzo/*.a ./lzo/*.o ./lzma/*.a ./lzma/*.o

cd ../libfdt/
rm *.o *.a

cd ../net/
rm *.o *.a

cd ../post/
rm *.o *.a

cd ../lib_arm/
rm *.o *.a

cd ../fs/
rm *.o *.a ./cramfs/*.a ./ext2/*.a ./fat/*.a ./fdos/*.a ./jffs2/*.a ./reiserfs/*.a ./ubifs/*.a ./yaffs2/*.a


cd ../examples/standalone/
rm *.bin *.a *.o *.srec

cd ../examples/standalone/
rm *.bin *.a *.o *.srec
cd ../

cd ../drivers/

rm ./video/*.o ./video/*.a

rm ./watchdog/*.o ./watchdog/*.a

rm ./usb/gadget/*.o ./usb/gadget/*.a
rm ./usb/host/*.o ./usb/host/*.a
rm ./usb/musb/*.o ./usb/musb/*.a

rm ./twserial/*.o ./twserial/*.a

rm ./spi/*.o ./spi/*.a

rm ./serial/*.o ./serial/*.a

rm ./rtc/*.o ./rtc/*.a

rm ./qe/*.o ./qe/*.a

rm ./power/*.o ./power/*.a

rm ./pcmcia/*.o ./pcmcia/*.a

rm ./pci/*.o ./pci/*.a

rm ./net/*.o ./net/*.a
rm ./net/phy/*.o ./net/phy/*.a
rm ./net/sk98lin/*.o ./net/sk98lin/*.a

rm ./mtd/*.o ./mtd/*.a
rm ./mtd/nand/*.o ./mtd/nand/*.a
rm ./mtd/onenand/*.o ./mtd/onenand/*.a
rm ./mtd/spi/*.o ./mtd/spi/*.a
rm ./mtd/ubi/*.o ./mtd/ubi/*.a

rm ./mmc/*.o ./mmc/*.a

rm ./misc/*.o ./misc/*.a

rm ./input/*.o ./input/*.a

rm ./i2c/*.o ./i2c/*.a

rm ./hwmon/*.o ./hwmon/*.a

rm ./gpio/*.o ./gpio/*.a

rm ./fpga/*.o ./fpga/*.a

rm ./dma/*.o ./dma/*.a

rm ./block/*.o ./block/*.a

rm ./bios_emulator/*.o ./bios_emulator/*.a
              
cd ../

rm ./disk/*.a ./disk/*.o

rm ./cpu/arm926ejs/*.a ./cpu/arm926ejs/*.o
rm ./cpu/arm926ejs/stmp378x/*.a ./cpu/arm926ejs/stmp378x/*.o

rm ./common/*.a ./common/*.o

rm ./board/stmp378x_dev/*.a ./board/stmp378x_dev/*.o

rm ./api/*.a ./api/*.o







